FROM python:3.8.12-slim


RUN mkdir -p /home/api
WORKDIR /home/api

ENV PORT '5000'

RUN apt-get update -y
RUN pip install -U --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python3", "app.py"]