#pragma once

enum EventEnum{
    PROGRAM_START,
    SERVER_CREATED,
    DEAMON_MODE_STARTED,
    SERVER_STARTED_PID,
    SIGNAL_HANDLER,
    PROGRAM_QUIT,
    ERROR_FILE_LOCK,
    USER_INPUT,
    USER_REQUEST
};
