name: Python tests

on:
  workflow_run:
    workflows: ["Make checker"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install openssl
      run: sudo apt-get install libssl-dev
    - name: make test
      run: sudo make test
